set_property SRC_FILE_INFO {cfile:/home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/constrs_1/imports/src/rvfpgabasys3.xdc rfile:../../../../../MinimalRVfpga.srcs/constrs_1/imports/src/rvfpgabasys3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name tck_dmi -add [get_pins tap/tap_dmi/TCK]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name tck_dtmcs -add [get_pins tap/tap_dtmcs/TCK]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name tck_idcode -add [get_pins tap/tap_idcode/DRCK]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfb -source [get_pins clk_gen/PLLE2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks sys_clk_pin] [get_pins clk_gen/PLLE2_BASE_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_core -source [get_pins clk_gen/PLLE2_BASE_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 35.000 70.000} -add -master_clock [get_clocks sys_clk_pin] [get_pins clk_gen/PLLE2_BASE_inst/CLKOUT0]
