# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-19218-jaime-laptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/gpio
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/ptc
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/WishboneInterconnect
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/BootROM/sw
  } {
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/common_defines.vh
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_pdef.vh
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cf_math_pkg.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/addr_decode.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_pkg.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_atop_filter.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_demux.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_err_slv.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_id_prepend.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/axi_intercon.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_intf.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_mux.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_xbar.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lib/beh_lib.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/bscan_tap.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/counter.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/delta_counter.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_def.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dbg/el2_dbg.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_decode_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_gpr_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_ib_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_tlu_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_trigger.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_dma_ctrl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu_alu_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_aln_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_bp_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_compress_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_ic_mem.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_iccm_mem.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_ifc_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_mem_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lib/el2_lib.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_addrcheck.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_bus_buffer.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_bus_intf.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_clkdomain.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_dccm_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_dccm_mem.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_ecc.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_lsc_ctl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_stbuf.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_trigger.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_mem.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_pic_ctrl.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_veer.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/deprecated/fifo_v2.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/fifo_v3.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/lzc.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lib/mem_lib.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/rr_arb_tree.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/spill_register.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/stream_register.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/veer_el2_wrapper.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/SystemController/veerwolf_syscon.sv
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/rvfpgabasys3.sv
    }
      rt::read_verilog -include {
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/gpio
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/ptc
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/WishboneInterconnect
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect
    /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/BootROM/sw
  } {
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/common_defines.vh
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiToWb/axi2wb.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/axi_ram.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/OtherSources/clk_gen_basys3.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/BootROM/dpram64.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/spi/fifo4.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/gpio/gpio_top.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/ptc/ptc_top.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/raminfr.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/spi/simple_spi_top.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_receiver.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_regs.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_rfifo.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_sync_flops.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_tfifo.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_top.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_transmitter.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_wb.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/veerwolf_core.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/BootROM/wb_mem_wrapper.v
      /home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.srcs/sources_1/imports/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon_1.2.2-r1/rtl/verilog/wb_mux.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-19218-jaime-laptop/realtime/rvfpgabasys3_synth.xdc
    rt::sdcChecksum
    set rt::top rvfpgabasys3
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/jaime/Desktop/Tese/Repository/Fault-Tolerant-Risc-V-Implementations/Minimal_RVfpga_EL2_Basys3/MinimalRVfpga/MinimalRVfpga.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-19218-jaime-laptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
